// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuDZcvOUSZFs0hGFzcdHqWFedhk7SSlYw',
    appId: '1:257499530818:web:c0d9f89c9d8c12cdfa0fdb',
    messagingSenderId: '257499530818',
    projectId: 'eventify-tech-d71b5',
    authDomain: 'eventify-tech-d71b5.firebaseapp.com',
    storageBucket: 'eventify-tech-d71b5.appspot.com',
    measurementId: 'G-645P81P98N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJo4-K3EYEXx9IwmVwDvTCKKBrvWniooY',
    appId: '1:257499530818:android:bba2a6a04422078efa0fdb',
    messagingSenderId: '257499530818',
    projectId: 'eventify-tech-d71b5',
    storageBucket: 'eventify-tech-d71b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbLy2IGN2KBDrJGVW8JkbtcMj-p6O7pUs',
    appId: '1:257499530818:ios:f9b355381d5649a4fa0fdb',
    messagingSenderId: '257499530818',
    projectId: 'eventify-tech-d71b5',
    storageBucket: 'eventify-tech-d71b5.appspot.com',
    iosBundleId: 'com.example.eventifyTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbLy2IGN2KBDrJGVW8JkbtcMj-p6O7pUs',
    appId: '1:257499530818:ios:f9b355381d5649a4fa0fdb',
    messagingSenderId: '257499530818',
    projectId: 'eventify-tech-d71b5',
    storageBucket: 'eventify-tech-d71b5.appspot.com',
    iosBundleId: 'com.example.eventifyTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuDZcvOUSZFs0hGFzcdHqWFedhk7SSlYw',
    appId: '1:257499530818:web:5d01e0e28555ec24fa0fdb',
    messagingSenderId: '257499530818',
    projectId: 'eventify-tech-d71b5',
    authDomain: 'eventify-tech-d71b5.firebaseapp.com',
    storageBucket: 'eventify-tech-d71b5.appspot.com',
    measurementId: 'G-WQ5ZKPPSFL',
  );
}
